# 기본 설정 파일
app:
  name: go-boilerplate
  version: 1.0.0
  port: 8080

# 로깅 설정
logging:
  level: info
  format: json
  output: stdout

# 데이터베이스 설정
database:
  host: localhost
  port: 5432
  name: go_boilerplate
  user: postgres
  password: postgres 